import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import NavBar from './NavBar';
import AuthProvider from './auth/Provider';
import GoogleAnalyticsScript from './GoogleAnalyticsScript';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] });
const poppins = localFont({
  src: '../public/fonts/poppins-regular-webfont.woff2',
});

export const metadata: Metadata = {
  title: 'This is root layout title',
  description: 'Generated by create next app',
  openGraph: {
    title: 'title for social media',
    description: 'description for social media',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      <body className={poppins.className}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
